# Generated by Django 3.0.4 on 2020-04-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_snippet_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='max_length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='min_length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='num_beams',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
