# Generated by Django 3.0.4 on 2020-04-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0005_auto_20200421_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='rouge',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
