# Generated by Django 3.0.4 on 2020-04-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0006_snippet_rouge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='rouge',
            field=models.TextField(),
        ),
    ]
